/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.ConexionDB;
import java.awt.Color;

/**
 *
 * @author JouCode
 */
public class FormMain extends javax.swing.JFrame {
    ConexionDB conex;
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        conex = new ConexionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_estudiante = new javax.swing.JButton();
        btn_profesor = new javax.swing.JButton();
        btn_adminsitrativo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_conexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);

        btn_estudiante.setText("Estudiante");
        btn_estudiante.setEnabled(false);
        btn_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudianteActionPerformed(evt);
            }
        });

        btn_profesor.setText("Profesor");
        btn_profesor.setEnabled(false);
        btn_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profesorActionPerformed(evt);
            }
        });

        btn_adminsitrativo.setText("Administrativo");
        btn_adminsitrativo.setEnabled(false);
        btn_adminsitrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminsitrativoActionPerformed(evt);
            }
        });

        jButton1.setText("Conectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_conexion.setForeground(new java.awt.Color(255, 0, 0));
        lbl_conexion.setText("Estado Desconectado....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_estudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_profesor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_adminsitrativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(lbl_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(lbl_conexion))
                .addGap(27, 27, 27)
                .addComponent(btn_estudiante)
                .addGap(18, 18, 18)
                .addComponent(btn_profesor)
                .addGap(18, 18, 18)
                .addComponent(btn_adminsitrativo)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudianteActionPerformed
        FormEstudiante form_student = new FormEstudiante();
        form_student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_estudianteActionPerformed

    private void btn_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profesorActionPerformed
        FormProfesor form_profe = new FormProfesor();
        form_profe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_profesorActionPerformed

    private void btn_adminsitrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminsitrativoActionPerformed
        FormAdministrativo form_admi = new FormAdministrativo();
        form_admi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_adminsitrativoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(conex.conectar()){
            lbl_conexion.setText("Estado conectado!");
            lbl_conexion.setForeground(Color.blue);
            btn_estudiante.setEnabled(true);
            btn_profesor.setEnabled(true);
            btn_adminsitrativo.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adminsitrativo;
    private javax.swing.JButton btn_estudiante;
    private javax.swing.JButton btn_profesor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_conexion;
    // End of variables declaration//GEN-END:variables
}
